# Change these first
owner: LeeYoungJin # Your GitHub organization or username, where this repository lives
repo: fg_upptime # The name of this repository

sites:
  - name: CompanyWise 기업현황
    url: https://comp.wisereport.co.kr/company/c1010001.aspx?cmp_cd=005930&cn=
  - name: CompanyWise 기업개요
    url: https://comp.wisereport.co.kr/company/c1020001.aspx?cmp_cd=005930&cn=
  - name: CompanyWise 재무분석
    url: https://comp.wisereport.co.kr/company/c1030001.aspx?cmp_cd=005930&cn=
  - name: CompanyWise 투자지
    url: https://comp.wisereport.co.kr/company/c1040001.aspx?cmp_cd=005930&cn=

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /fg_upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: fg_upptime
  introTitle: "웹 상태"
  introMessage: 웹 서버 상태 확인 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
