# Change these first
owner: LeeYoungJin # Your GitHub organization or username, where this repository lives
repo: fg_upptime # The name of this repository

sites:
  - name: WiseReport1
    url: https://www1.wisereport.co.kr/servercheck.aspx
  - name: WiseReport2
    url: https://www2.wisereport.co.kr/servercheck.aspx
  - name: WiseReport3
    url: https://www3.wisereport.co.kr/servercheck.aspx

        

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /fg_upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: fg_upptime
  introTitle: "웹 상태"
  introMessage: 웹 서버 상태 확인 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
